/gps/particle mu-
/gps/number 1
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 0.0 0.0 0.0 cm

/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 0 1
/gps/pos/halfx 1.0 cm
/gps/pos/halfy 1.0 cm
/gps/direction 0.0 0.0 -1.0

/gps/ene/type Arb
/gps/hist/type arb
/gps/hist/point 1000 .363
/gps/hist/point 2000 .162
/gps/hist/point 3000 .094
/gps/hist/point 5000 .043
/gps/hist/point 10000 .011
/gps/hist/point 20000 .002
/gps/hist/inter Lin
