/control/verbose 2
/control/saveHistory

/gps/particle opticalphoton
/gps/number 1
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 0.35 mm
/gps/pos/centre 0 0 5 cm
/gps/direction 0.0 0.0 -1.0
/gps/ang/type beam1d
/gps/ang/sigma_r 5 deg
/gps/ene/mono 3.1 eV

/Nova/detector/length 0.1 m
/Nova/detector/update
/Nova/detector/printSetting

/tracking/verbose 1
/run/verbose 2
/run/initialize
/run/beamOn 20
